"""Add expiration fields to VaultItem

Revision ID: 212fa30c3994
Revises: 89aec76eade3
Create Date: 2024-12-04 21:40:24.001200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212fa30c3994'
down_revision = '89aec76eade3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_expiration', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('passport_expiration', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('license_expiration', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_item', schema=None) as batch_op:
        batch_op.drop_column('license_expiration')
        batch_op.drop_column('passport_expiration')
        batch_op.drop_column('credit_card_expiration')

    # ### end Alembic commands ###
