"""Add url column to VaultItem

Revision ID: 98c654f6bc7f
Revises: c049e2246000
Create Date: 2024-12-04 17:46:48.541165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c654f6bc7f'
down_revision = 'c049e2246000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_item', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
