"""Initial migration

Revision ID: c049e2246000
Revises: 
Create Date: 2024-12-04 15:46:23.900386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c049e2246000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('master_password', sa.String(length=120), nullable=False),
    sa.Column('security_q1', sa.String(length=120), nullable=False),
    sa.Column('security_a1', sa.String(length=120), nullable=False),
    sa.Column('security_q2', sa.String(length=120), nullable=False),
    sa.Column('security_a2', sa.String(length=120), nullable=False),
    sa.Column('security_q3', sa.String(length=120), nullable=False),
    sa.Column('security_a3', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vault_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('credit_card_number', sa.String(length=16), nullable=True),
    sa.Column('cvv', sa.String(length=4), nullable=True),
    sa.Column('secure_note', sa.Text(), nullable=True),
    sa.Column('masked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_item')
    op.drop_table('notification')
    op.drop_table('user')
    # ### end Alembic commands ###
